name: Build and Test

on: [push, workflow_dispatch]

jobs:
  build:
    name: ${{ matrix.os }} / ${{ matrix.async }}
    strategy:
      matrix:
        include:
          # NOTE: Temporarily disabled epoll and kevent due to same flakiness in tests.
          # - os: ubuntu-latest
          #   async: epoll
          # - os: macos-latest
          #   async: kevent
          - os: ubuntu-latest
            async: uring

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Build Environment
        run: ./ck tools setup && ./ck tools doctor

      - name: Instal Externs
        run: ./ck install

      - name: Build Libraries
        run: ./ck build --props:async=${{ matrix.async }}

      - name: Test Libraries
        run: ./ck test --props:async=${{ matrix.async }}

      - name: Run Reftests
        run: ./ck reftests run --headless --props:async=${{ matrix.async }}
