name: Build and Test

on: [push, workflow_dispatch]

jobs:
  build:
    name: ${{ matrix.os }} / ${{ matrix.async }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            async: epoll
          - os: ubuntu-latest
            async: uring
          - os: macos-latest
            async: kevent

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Build Environment
        run: ./ck tools setup && ./ck tools doctor

      - name: Build Libraries
        run: ./ck build --props:async=${{ matrix.async }}

      - name: Test Libraries
        run: ./ck test --props:async=${{ matrix.async }}

      - name: Run Reftests
        run: ./ck reftests run --headless --props:async=${{ matrix.async }}
